name: UserFrosting
highlighter: pygments
baseurl: /
title: UserFrosting
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
